Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 30

Metrics/ClassLength:
  Max: 120

Metrics/CyclomaticComplexity:
  Max: 9

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - spec/**/*
