Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 155

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 30

Metrics/AbcSize:
  Max: 30

Metrics/ClassLength:
  Max: 120

Metrics/BlockLength:
  Max: 40

Metrics/CyclomaticComplexity:
  Max: 9
